//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PageNumber { get; set; }
        public int BookSeriesId { get; set; }
        public int PublisherHouseId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookSerie BookSery { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
    }
}
