//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDal.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFLibraryDbContext : DbContext
    {
        public EFLibraryDbContext()
            : base("name=EFLibraryDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookSerie> BookSeries1 { get; set; }
        public virtual DbSet<PublishingHouse> PublishingHouses { get; set; }
        public virtual DbSet<AuthorsStatistic> AuthorsStatistics { get; set; }
        public virtual DbSet<AuthorView> AuthorViews { get; set; }
        public virtual DbSet<BookSeriesStatistic> BookSeriesStatistics { get; set; }
        public virtual DbSet<BookSeriesView> BookSeriesViews { get; set; }
        public virtual DbSet<BooksView> BooksViews { get; set; }
        public virtual DbSet<PublishingHousesStatistic> PublishingHousesStatistics { get; set; }
        public virtual DbSet<PublishingHouseView> PublishingHouseViews { get; set; }
    }
}
